# Generated by Django 4.2 on 2024-04-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='uploaded_file',
            field=models.TextField(),
        ),
    ]
