# Generated by Django 4.2 on 2024-04-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userfile_uploaded_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='userfile',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
