# Generated by Django 4.2 on 2025-04-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_lesson_section_testscore_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='end_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
